### ISSUE TITLE
"Error: The library name can not be empty or null." when running library.sh on fresh clone

### ISSUE THREAD

**Issue by kkukshtel** [bottlenoselabs/sokol-cs#108]
Exactly as stated in the title — cloning the library and running `sh ./library.sh` results in the following output:

```
'/Users/kyle/Workspace/sokol-cs/ext/scripts/c/library/main.sh': Validating input...
	1=/Users/kyle/Workspace/sokol-cs/src/c/sokol
	2=/Users/kyle/Workspace/sokol-cs/lib
	3=sokol
	4=
	5=
	6=
	7=
```

It seems like there is another argument missing but I can't find documentation of it either in here or in the C2CS project. Let me know if you need any other info.

**Comment by kkukshtel** [comment]
Also looking at the configured Github actions it seems like they are also failing on the DLL build jobs:

https://github.com/bottlenoselabs/sokol-cs/actions/runs/2566284664

**Comment by lithiumtoast** [comment]
@kkukshtel Fixed; tested locally and the workflow is passing on GitHub
